name: Deploy to GCR

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: Configure Docker for Artifact Registry
        run: |
            gcloud auth configure-docker gcr.io
            gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/calcium-field-448820-a9/therapist:$GITHUB_SHA .
          docker push gcr.io/calcium-field-448820-a9/therapist:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy therapist \
            --image gcr.io/calcium-field-448820-a9/therapist:$GITHUB_SHA \
            --region us-east4 \
            --platform managed \
            --allow-unauthenticated
