name: Deploy to GCR

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2

      - name: Configure Docker
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/calcium-field-448820-a9/therapist:$GITHUB_SHA .
          docker push gcr.io/calcium-field-448820-a9/therapist:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy therapist \
            --image gcr.io/calcium-field-448820-a9/therapist:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
